name: Update CSVs from Google Sheets

on:
  push:
    branches:
      - 'main'
# on:
#   schedule:
#     - cron: '*/15 * * * *'
#   workflow_dispatch:

jobs:
  update-csvs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Update CSVs from Google Sheets
        run: python scripts/update_csvs_from_sheets.py "${{ secrets.GSHEET_URL }}" "${{ secrets.GSHEET_CREDENTIALS_JSON }}"
        working-directory: .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Update CSVs from Google Sheets" || echo "No changes to commit"
          git push
